image: "python:3.9"
#commands to run in the Docker container before starting each job.
before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
# different stages in the pipeline
stages:
  - deploy
#defines the job

prod_notification_service:
  stage: deploy
  only:
    refs:
      - main
  script:
    - curl https://tumor.informatics.jax.org/PDXInfo/PDXInfoTSV/PDXNetAllModels.tsv >> temp/temp.tsv
    - python3 main.py